fint:
  kafka:
    topic:
      org-id: fintlabs.no
      domain-context: flyt
    application-id: fint-flyt-test-instance-gateway
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-flyt-test-instance-gateway
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
server:
  port: 8089